# Generated by Django 5.2.9 on 2025-12-30 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_order_payment_remove_payment_stripe_charge_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="core.order",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider",
            field=models.CharField(
                choices=[("stripe", "Stripe"), ("paypal", "PayPal")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="provider_payment_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
