# Generated by Django 5.2.8 on 2025-11-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0002_todo_add_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
