# Generated by Django 5.2.9 on 2025-12-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="search",
            options={"verbose_name_plural": "Searches"},
        ),
        migrations.AlterField(
            model_name="search",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
